<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApplicantSkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('applicant_skill')->insert([
            ['applicant_id' => 63, 'skill_id' => 0],
            ['applicant_id' => 63, 'skill_id' => 1],
            ['applicant_id' => 63, 'skill_id' => 2],
            ['applicant_id' => 63, 'skill_id' => 3],
            ['applicant_id' => 63, 'skill_id' => 4],
            ['applicant_id' => 63, 'skill_id' => 5],
            ['applicant_id' => 63, 'skill_id' => 6],
            ['applicant_id' => 63, 'skill_id' => 7],
            ['applicant_id' => 63, 'skill_id' => 8],

            ['applicant_id' => 64, 'skill_id' => 0],
            ['applicant_id' => 64, 'skill_id' => 1],
            ['applicant_id' => 64, 'skill_id' => 2],
            ['applicant_id' => 64, 'skill_id' => 3],
            ['applicant_id' => 64, 'skill_id' => 4],
            ['applicant_id' => 64, 'skill_id' => 5],
            ['applicant_id' => 64, 'skill_id' => 6],
            ['applicant_id' => 64, 'skill_id' => 7],
            ['applicant_id' => 64, 'skill_id' => 8],

            ['applicant_id' => 65, 'skill_id' => 0],
            ['applicant_id' => 65, 'skill_id' => 1],
            ['applicant_id' => 65, 'skill_id' => 2],
            ['applicant_id' => 65, 'skill_id' => 3],
            ['applicant_id' => 65, 'skill_id' => 4],
            ['applicant_id' => 65, 'skill_id' => 5],
            ['applicant_id' => 65, 'skill_id' => 6],
            ['applicant_id' => 65, 'skill_id' => 7],
            ['applicant_id' => 65, 'skill_id' => 8],

            ['applicant_id' => 66, 'skill_id' => 0],
            ['applicant_id' => 66, 'skill_id' => 1],
            ['applicant_id' => 66, 'skill_id' => 2],
            ['applicant_id' => 66, 'skill_id' => 3],
            ['applicant_id' => 66, 'skill_id' => 4],
            ['applicant_id' => 66, 'skill_id' => 5],
            ['applicant_id' => 66, 'skill_id' => 6],
            ['applicant_id' => 66, 'skill_id' => 7],
            ['applicant_id' => 66, 'skill_id' => 8],

            ['applicant_id' => 67, 'skill_id' => 0],
            ['applicant_id' => 67, 'skill_id' => 1],
            ['applicant_id' => 67, 'skill_id' => 2],
            ['applicant_id' => 67, 'skill_id' => 3],
            ['applicant_id' => 67, 'skill_id' => 4],
            ['applicant_id' => 67, 'skill_id' => 5],
            ['applicant_id' => 67, 'skill_id' => 6],
            ['applicant_id' => 67, 'skill_id' => 7],
            ['applicant_id' => 67, 'skill_id' => 8],

            ['applicant_id' => 68, 'skill_id' => 0],
            ['applicant_id' => 68, 'skill_id' => 1],
            ['applicant_id' => 68, 'skill_id' => 2],
            ['applicant_id' => 68, 'skill_id' => 3],
            ['applicant_id' => 68, 'skill_id' => 4],
            ['applicant_id' => 68, 'skill_id' => 5],
            ['applicant_id' => 68, 'skill_id' => 6],
            ['applicant_id' => 68, 'skill_id' => 7],
            ['applicant_id' => 68, 'skill_id' => 8],

            ['applicant_id' => 69, 'skill_id' => 0],
            ['applicant_id' => 69, 'skill_id' => 1],
            ['applicant_id' => 69, 'skill_id' => 2],
            ['applicant_id' => 69, 'skill_id' => 3],
            ['applicant_id' => 69, 'skill_id' => 4],
            ['applicant_id' => 69, 'skill_id' => 5],
            ['applicant_id' => 69, 'skill_id' => 6],
            ['applicant_id' => 69, 'skill_id' => 7],
            ['applicant_id' => 69, 'skill_id' => 8],

            ['applicant_id' => 70, 'skill_id' => 0],
            ['applicant_id' => 70, 'skill_id' => 1],
            ['applicant_id' => 70, 'skill_id' => 2],
            ['applicant_id' => 70, 'skill_id' => 3],
            ['applicant_id' => 70, 'skill_id' => 4],
            ['applicant_id' => 70, 'skill_id' => 5],
            ['applicant_id' => 70, 'skill_id' => 6],
            ['applicant_id' => 70, 'skill_id' => 7],
            ['applicant_id' => 70, 'skill_id' => 8],

            ['applicant_id' => 71, 'skill_id' => 0],
            ['applicant_id' => 71, 'skill_id' => 1],
            ['applicant_id' => 71, 'skill_id' => 2],
            ['applicant_id' => 71, 'skill_id' => 3],
            ['applicant_id' => 71, 'skill_id' => 4],
            ['applicant_id' => 71, 'skill_id' => 5],
            ['applicant_id' => 71, 'skill_id' => 6],
            ['applicant_id' => 71, 'skill_id' => 7],
            ['applicant_id' => 71, 'skill_id' => 8],

            ['applicant_id' => 72, 'skill_id' => 0],
            ['applicant_id' => 72, 'skill_id' => 1],
            ['applicant_id' => 72, 'skill_id' => 2],
            ['applicant_id' => 72, 'skill_id' => 3],
            ['applicant_id' => 72, 'skill_id' => 4],
            ['applicant_id' => 72, 'skill_id' => 5],
            ['applicant_id' => 72, 'skill_id' => 6],
            ['applicant_id' => 72, 'skill_id' => 7],
            ['applicant_id' => 72, 'skill_id' => 8],

            ['applicant_id' => 73, 'skill_id' => 0],
            ['applicant_id' => 73, 'skill_id' => 1],
            ['applicant_id' => 73, 'skill_id' => 2],
            ['applicant_id' => 73, 'skill_id' => 3],
            ['applicant_id' => 73, 'skill_id' => 4],
            ['applicant_id' => 73, 'skill_id' => 5],
            ['applicant_id' => 73, 'skill_id' => 6],
            ['applicant_id' => 73, 'skill_id' => 7],
            ['applicant_id' => 73, 'skill_id' => 8],

            ['applicant_id' => 74, 'skill_id' => 0],
            ['applicant_id' => 74, 'skill_id' => 1],
            ['applicant_id' => 74, 'skill_id' => 2],
            ['applicant_id' => 74, 'skill_id' => 3],
            ['applicant_id' => 74, 'skill_id' => 4],
            ['applicant_id' => 74, 'skill_id' => 5],
            ['applicant_id' => 74, 'skill_id' => 6],
            ['applicant_id' => 74, 'skill_id' => 7],
            ['applicant_id' => 74, 'skill_id' => 8],

            ['applicant_id' => 75, 'skill_id' => 0],
            ['applicant_id' => 75, 'skill_id' => 1],
            ['applicant_id' => 75, 'skill_id' => 2],
            ['applicant_id' => 75, 'skill_id' => 3],
            ['applicant_id' => 75, 'skill_id' => 4],
            ['applicant_id' => 75, 'skill_id' => 5],
            ['applicant_id' => 75, 'skill_id' => 6],
            ['applicant_id' => 75, 'skill_id' => 7],
            ['applicant_id' => 75, 'skill_id' => 8],

            ['applicant_id' => 76, 'skill_id' => 0],
            ['applicant_id' => 76, 'skill_id' => 1],
            ['applicant_id' => 76, 'skill_id' => 2],
            ['applicant_id' => 76, 'skill_id' => 3],
            ['applicant_id' => 76, 'skill_id' => 4],
            ['applicant_id' => 76, 'skill_id' => 5],
            ['applicant_id' => 76, 'skill_id' => 6],
            ['applicant_id' => 76, 'skill_id' => 7],
            ['applicant_id' => 76, 'skill_id' => 8],

            ['applicant_id' => 77, 'skill_id' => 0],
            ['applicant_id' => 77, 'skill_id' => 1],
            ['applicant_id' => 77, 'skill_id' => 2],
            ['applicant_id' => 77, 'skill_id' => 3],
            ['applicant_id' => 77, 'skill_id' => 4],
            ['applicant_id' => 77, 'skill_id' => 5],
            ['applicant_id' => 77, 'skill_id' => 6],
            ['applicant_id' => 77, 'skill_id' => 7],
            ['applicant_id' => 77, 'skill_id' => 8],

            ['applicant_id' => 78, 'skill_id' => 0],
            ['applicant_id' => 78, 'skill_id' => 1],
            ['applicant_id' => 78, 'skill_id' => 2],
            ['applicant_id' => 78, 'skill_id' => 3],
            ['applicant_id' => 78, 'skill_id' => 4],
            ['applicant_id' => 78, 'skill_id' => 5],
            ['applicant_id' => 78, 'skill_id' => 6],
            ['applicant_id' => 78, 'skill_id' => 7],
            ['applicant_id' => 78, 'skill_id' => 8],

            ['applicant_id' => 79, 'skill_id' => 0],
            ['applicant_id' => 79, 'skill_id' => 1],
            ['applicant_id' => 79, 'skill_id' => 2],
            ['applicant_id' => 79, 'skill_id' => 3],
            ['applicant_id' => 79, 'skill_id' => 4],
            ['applicant_id' => 79, 'skill_id' => 5],
            ['applicant_id' => 79, 'skill_id' => 6],
            ['applicant_id' => 79, 'skill_id' => 7],
            ['applicant_id' => 79, 'skill_id' => 8],

            ['applicant_id' => 80, 'skill_id' => 0],
            ['applicant_id' => 80, 'skill_id' => 1],
            ['applicant_id' => 80, 'skill_id' => 2],
            ['applicant_id' => 80, 'skill_id' => 3],
            ['applicant_id' => 80, 'skill_id' => 4],
            ['applicant_id' => 80, 'skill_id' => 5],
            ['applicant_id' => 80, 'skill_id' => 6],
            ['applicant_id' => 80, 'skill_id' => 7],
            ['applicant_id' => 80, 'skill_id' => 8],

            ['applicant_id' => 81, 'skill_id' => 0],
            ['applicant_id' => 81, 'skill_id' => 1],
            ['applicant_id' => 81, 'skill_id' => 2],
            ['applicant_id' => 81, 'skill_id' => 3],
            ['applicant_id' => 81, 'skill_id' => 4],
            ['applicant_id' => 81, 'skill_id' => 5],
            ['applicant_id' => 81, 'skill_id' => 6],
            ['applicant_id' => 81, 'skill_id' => 7],
            ['applicant_id' => 81, 'skill_id' => 8],

            ['applicant_id' => 82, 'skill_id' => 0],
            ['applicant_id' => 82, 'skill_id' => 1],
            ['applicant_id' => 82, 'skill_id' => 2],
            ['applicant_id' => 82, 'skill_id' => 3],
            ['applicant_id' => 82, 'skill_id' => 4],
            ['applicant_id' => 82, 'skill_id' => 5],
            ['applicant_id' => 82, 'skill_id' => 6],
            ['applicant_id' => 82, 'skill_id' => 7],
            ['applicant_id' => 82, 'skill_id' => 8],

            ['applicant_id' => 83, 'skill_id' => 0],
            ['applicant_id' => 83, 'skill_id' => 1],
            ['applicant_id' => 83, 'skill_id' => 2],
            ['applicant_id' => 83, 'skill_id' => 3],
            ['applicant_id' => 83, 'skill_id' => 4],
            ['applicant_id' => 83, 'skill_id' => 5],
            ['applicant_id' => 83, 'skill_id' => 6],
            ['applicant_id' => 83, 'skill_id' => 7],
            ['applicant_id' => 83, 'skill_id' => 8],

            ['applicant_id' => 84, 'skill_id' => 0],
            ['applicant_id' => 84, 'skill_id' => 1],
            ['applicant_id' => 84, 'skill_id' => 2],
            ['applicant_id' => 84, 'skill_id' => 3],
            ['applicant_id' => 84, 'skill_id' => 4],
            ['applicant_id' => 84, 'skill_id' => 5],
            ['applicant_id' => 84, 'skill_id' => 6],
            ['applicant_id' => 84, 'skill_id' => 7],
            ['applicant_id' => 84, 'skill_id' => 8],

            ['applicant_id' => 85, 'skill_id' => 0],
            ['applicant_id' => 85, 'skill_id' => 1],
            ['applicant_id' => 85, 'skill_id' => 2],
            ['applicant_id' => 85, 'skill_id' => 3],
            ['applicant_id' => 85, 'skill_id' => 4],
            ['applicant_id' => 85, 'skill_id' => 5],
            ['applicant_id' => 85, 'skill_id' => 6],
            ['applicant_id' => 85, 'skill_id' => 7],
            ['applicant_id' => 85, 'skill_id' => 8],

            ['applicant_id' => 86, 'skill_id' => 0],
            ['applicant_id' => 86, 'skill_id' => 1],
            ['applicant_id' => 86, 'skill_id' => 2],
            ['applicant_id' => 86, 'skill_id' => 3],
            ['applicant_id' => 86, 'skill_id' => 4],
            ['applicant_id' => 86, 'skill_id' => 5],
            ['applicant_id' => 86, 'skill_id' => 6],
            ['applicant_id' => 86, 'skill_id' => 7],
            ['applicant_id' => 86, 'skill_id' => 8],

            ['applicant_id' => 87, 'skill_id' => 0],
            ['applicant_id' => 87, 'skill_id' => 1],
            ['applicant_id' => 87, 'skill_id' => 2],
            ['applicant_id' => 87, 'skill_id' => 3],
            ['applicant_id' => 87, 'skill_id' => 4],
            ['applicant_id' => 87, 'skill_id' => 5],
            ['applicant_id' => 87, 'skill_id' => 6],
            ['applicant_id' => 87, 'skill_id' => 7],
            ['applicant_id' => 87, 'skill_id' => 8],

            ['applicant_id' => 88, 'skill_id' => 0],
            ['applicant_id' => 88, 'skill_id' => 1],
            ['applicant_id' => 88, 'skill_id' => 2],
            ['applicant_id' => 88, 'skill_id' => 3],
            ['applicant_id' => 88, 'skill_id' => 4],
            ['applicant_id' => 88, 'skill_id' => 5],
            ['applicant_id' => 88, 'skill_id' => 6],
            ['applicant_id' => 88, 'skill_id' => 7],
            ['applicant_id' => 88, 'skill_id' => 8],

            ['applicant_id' => 89, 'skill_id' => 0],
            ['applicant_id' => 89, 'skill_id' => 1],
            ['applicant_id' => 89, 'skill_id' => 2],
            ['applicant_id' => 89, 'skill_id' => 3],
            ['applicant_id' => 89, 'skill_id' => 4],
            ['applicant_id' => 89, 'skill_id' => 5],
            ['applicant_id' => 89, 'skill_id' => 6],
            ['applicant_id' => 89, 'skill_id' => 7],
            ['applicant_id' => 89, 'skill_id' => 8],

            ['applicant_id' => 90, 'skill_id' => 0],
            ['applicant_id' => 90, 'skill_id' => 1],
            ['applicant_id' => 90, 'skill_id' => 2],
            ['applicant_id' => 90, 'skill_id' => 3],
            ['applicant_id' => 90, 'skill_id' => 4],
            ['applicant_id' => 90, 'skill_id' => 5],
            ['applicant_id' => 90, 'skill_id' => 6],
            ['applicant_id' => 90, 'skill_id' => 7],
            ['applicant_id' => 90, 'skill_id' => 8],

            ['applicant_id' => 91, 'skill_id' => 0],
            ['applicant_id' => 91, 'skill_id' => 1],
            ['applicant_id' => 91, 'skill_id' => 2],
            ['applicant_id' => 91, 'skill_id' => 3],
            ['applicant_id' => 91, 'skill_id' => 4],
            ['applicant_id' => 91, 'skill_id' => 5],
            ['applicant_id' => 91, 'skill_id' => 6],
            ['applicant_id' => 91, 'skill_id' => 7],
            ['applicant_id' => 91, 'skill_id' => 8],

            ['applicant_id' => 92, 'skill_id' => 0],
            ['applicant_id' => 92, 'skill_id' => 1],
            ['applicant_id' => 92, 'skill_id' => 2],
            ['applicant_id' => 92, 'skill_id' => 3],
            ['applicant_id' => 92, 'skill_id' => 4],
            ['applicant_id' => 92, 'skill_id' => 5],
            ['applicant_id' => 92, 'skill_id' => 6],
            ['applicant_id' => 92, 'skill_id' => 7],
            ['applicant_id' => 92, 'skill_id' => 8],

            ['applicant_id' => 93, 'skill_id' => 0],
            ['applicant_id' => 93, 'skill_id' => 1],
            ['applicant_id' => 93, 'skill_id' => 2],
            ['applicant_id' => 93, 'skill_id' => 3],
            ['applicant_id' => 93, 'skill_id' => 4],
            ['applicant_id' => 93, 'skill_id' => 5],
            ['applicant_id' => 93, 'skill_id' => 6],
            ['applicant_id' => 93, 'skill_id' => 7],
            ['applicant_id' => 93, 'skill_id' => 8],

            ['applicant_id' => 94, 'skill_id' => 0],
            ['applicant_id' => 94, 'skill_id' => 1],
            ['applicant_id' => 94, 'skill_id' => 2],
            ['applicant_id' => 94, 'skill_id' => 3],
            ['applicant_id' => 94, 'skill_id' => 4],
            ['applicant_id' => 94, 'skill_id' => 5],
            ['applicant_id' => 94, 'skill_id' => 6],
            ['applicant_id' => 94, 'skill_id' => 7],
            ['applicant_id' => 94, 'skill_id' => 8],

            ['applicant_id' => 95, 'skill_id' => 0],
            ['applicant_id' => 95, 'skill_id' => 1],
            ['applicant_id' => 95, 'skill_id' => 2],
            ['applicant_id' => 95, 'skill_id' => 3],
            ['applicant_id' => 95, 'skill_id' => 4],
            ['applicant_id' => 95, 'skill_id' => 5],
            ['applicant_id' => 95, 'skill_id' => 6],
            ['applicant_id' => 95, 'skill_id' => 7],
            ['applicant_id' => 95, 'skill_id' => 8],
        ]);
    }
}
