<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('companies')->insert([
            [
                "id" => 0,
                "name" => "Innovize",
                "email" => "contact@innovize.com",
                "phone" => "+49 152 89674321",
                "description" => "Innovize is a leading software development company specializing in creating innovative and customized solutions for businesses of all sizes. With a team of experienced developers, designers, and project managers, Innovize prides itself on delivering high-quality software products that meet the unique needs and requirements of each client. Founded in 2009, Innovize has quickly become a trusted partner for companies looking to streamline their operations, improve efficiency, and enhance their digital presence. From web and mobile app development to cloud solutions and e-commerce platforms, Innovize offers a wide range of services to help businesses succeed in today's fast-paced digital landscape. At Innovize, we are committed to staying ahead of the curve and continually evolving our technologies to meet the changing demands of the market. Our agile development approach allows us to quickly adapt to new trends and technologies, ensuring that our clients always have access to the most cutting-edge solutions available. Whether you are a small startup or a large enterprise, Innovize has the expertise and capabilities to turn your vision into reality. Contact us today to learn more about how we can help you take your business to the next level.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "innovize",
                "linkedin" => "innovize",
                "twitter" => "innovize",
                "website" => "https://innovize.com",
                "avatar" => "innovize.svg",
                "slug" => "innovize",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 1,
                "name" => "Samsung Electronics",
                "email" => "contact@samsung.com",
                "phone" => "+49 152 89674321",
                "description" => "Samsung Electronics is a global leader in technology innovation, delivering cutting-edge products and services that are redefining the way we live and work. With a rich heritage of over 80 years, Samsung is committed to providing consumers with innovative and reliable solutions in various fields, including consumer electronics, semiconductors, telecommunications, and home appliances. Our mission is to inspire the world with innovative technologies, products, and designs that enrich people's lives. Join us and be part of a team that continues to shape the future of technology. To apply, please submit your resume and a cover letter highlighting your relevant experience to [email address]. We thank all applicants, but only those selected for an interview will be contacted. Samsung Electronics is an equal opportunity employer. We celebrate diversity and are committed to creating an inclusive environment for all employees.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "samsung",
                "linkedin" => "samsung",
                "twitter" => "samsung",
                "website" => "https://samsung.com",
                "avatar" => "samsung.svg",
                "slug" => "samsung",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 2,
                "name" => "Tesla, Inc.",
                "email" => "contact@tesla.com",
                "phone" => "+49 152 89674321",
                "description" => "Tesla, Inc. is a leading electric vehicle and clean energy company founded in 2003. Our mission is to accelerate the world's transition to sustainable energy. We design, manufacture, and sell electric vehicles, renewable energy storage solutions, and solar products. At Tesla, we strive to create a sustainable future by revolutionizing the transportation and energy industries. Join us and be part of the team that is shaping the future of mobility and sustainability.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "tesla",
                "linkedin" => "tesla",
                "twitter" => "tesla",
                "website" => "https://tesla.com",
                "avatar" => "tesla.svg",
                "slug" => "tesla",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 3,
                "name" => "Spotify",
                "email" => "contact@spotify.com",
                "phone" => "+49 152 89674321",
                "description" => "Spotify is a leading music streaming platform that connects millions of users to their favorite songs, podcasts, and artists. Our mission is to unlock the potential of human creativity by giving a million creative artists the opportunity to live off their art while providing users with a personalized music experience they can enjoy anytime, anywhere. With a diverse and talented team of engineers, designers, and music enthusiasts, we are committed to revolutionizing the way people discover, listen to, and share music.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "spotify",
                "linkedin" => "spotify",
                "twitter" => "spotify",
                "website" => "https://spotify.com",
                "avatar" => "spotify.svg",
                "slug" => "spotify",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 4,
                "name" => "IBM",
                "email" => "contact@ibm.com",
                "phone" => "+49 152 89674321",
                "description" => "IBM is a leading technology company that provides innovative solutions to businesses across various industries. With a strong focus on advancing technology and driving digital transformation, IBM is committed to helping clients leverage data for meaningful insights and competitive advantage. As an employee at IBM, you will be part of a diverse and inclusive workforce, collaborating with talented professionals from around the world to shape the future of technology.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "ibm",
                "linkedin" => "ibm",
                "twitter" => "ibm",
                "website" => "https://ibm.com",
                "avatar" => "ibm.svg",
                "slug" => "ibm",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 5,
                "name" => "SAP",
                "email" => "contact@sap.com",
                "phone" => "+49 152 89674321",
                "description" => "SAP is a global market leader in enterprise application software, helping organizations streamline their business processes and empower their employees, partners, and customers. With more than 440,000 customers in over 180 countries, SAP provides a diverse portfolio of solutions that span from on-premise to cloud-based platforms. As a company committed to innovation, SAP embraces diversity and inclusion, fosters a culture of continuous learning, and actively supports social and environmental responsibility. Join our team to make an impact on the digital transformation of businesses worldwide.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "sap",
                "linkedin" => "sap",
                "twitter" => "sap",
                "website" => "https://sap.com",
                "avatar" => "sap.svg",
                "slug" => "sap",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 6,
                "name" => "Salesforce Inc",
                "email" => "contact@salesforce.com",
                "phone" => "+49 152 89674321",
                "description" => "Salesforce Inc is a leading cloud computing company that specializes in customer relationship management (CRM) software solutions. Our innovative products and services help businesses of all sizes to connect with customers, partners, and employees in entirely new ways. With over 150,000 customers worldwide, we are committed to delivering exceptional customer experiences by providing cutting-edge technology solutions. Our company culture is built on trust, transparency, and collaboration, where employees are empowered to make a meaningful impact and drive positive change. Join Salesforce and be part of a dynamic team that is shaping the future of software development.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "salesforce",
                "linkedin" => "salesforce",
                "twitter" => "salesforce",
                "website" => "https://salesforce.com",
                "avatar" => "salesforce.svg",
                "slug" => "salesforce",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 7,
                "name" => "JPMorgan Chase & Co",
                "email" => "contact@jpmorgan-chase.com",
                "phone" => "+49 152 89674321",
                "description" => "JPMorgan Chase is a multinational investment bank and financial services company headquartered in the United States. With a rich history dating back over 200 years, JPMorgan Chase has established itself as one of the leading financial institutions globally. The company offers a wide range of financial services, including investment banking, asset management, private banking, and consumer and commercial banking. It caters to a diverse client base, including individuals, corporations, governments, and institutional investors. JPMorgan Chase is known for its commitment to innovation and technology. The company actively embraces digital transformation to enhance its customer experience and streamline its operations. It invests heavily in research and development, leveraging cutting-edge technologies to develop market-leading products and services.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "jpmorgan-chase",
                "linkedin" => "jpmorgan-chase",
                "twitter" => "jpmorgan-chase",
                "website" => "https://jpmorgan-chase.com",
                "avatar" => "jpmorgan-chase.svg",
                "slug" => "jpmorgan-chase",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 8,
                "name" => "Pfizer",
                "email" => "contact@pfizer.com",
                "phone" => "+49 152 89674321",
                "description" => "Pfizer is one of the world's premier pharmaceutical companies, dedicated to discovering, developing, and manufacturing breakthrough medicines to improve people's health and wellbeing. With a rich history spanning over 170 years, Pfizer has established itself as a global leader in the healthcare industry, with a focus on innovative research, quality manufacturing, and compassionate patient care. Joining Pfizer means being part of a diverse and inclusive team that strives to make a positive impact on society and bring meaningful treatments to patients worldwide.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "pfizer",
                "linkedin" => "pfizer",
                "twitter" => "pfizer",
                "website" => "https://pfizer.com",
                "avatar" => "pfizer.svg",
                "slug" => "pfizer",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 9,
                "name" => "Johnson & Johnson",
                "email" => "contact@johnson&johnson.com",
                "phone" => "+49 152 89674321",
                "description" => "Johnson & Johnson is a global healthcare company driven by a purpose to improve the health and well-being of people worldwide. With a rich heritage of over 135 years, we are dedicated to delivering innovative solutions that address the evolving health needs of individuals and communities. Our diverse portfolio includes pharmaceuticals, medical devices, and consumer health products. We embrace a culture of collaboration, diversity, and inclusion, and strive to create an environment where all employees can thrive and make a meaningful impact. Join us in our commitment to advancing healthcare and shaping the future of medical innovation.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "johnson&johnson",
                "linkedin" => "johnson&johnson",
                "twitter" => "johnson&johnson",
                "website" => "https://johnson&johnson.com",
                "avatar" => "johnson&johnson.svg",
                "slug" => "johnson&johnson",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 10,
                "name" => "Sony Corporation",
                "email" => "contact@sony.com",
                "phone" => "+49 152 89674321",
                "description" => "Sony Corporation is a global leader in technology and entertainment, dedicated to delivering high-quality products and services across various sectors. With a rich history of innovation, Sony's mission is to inspire and fulfill the curiosity of people around the world. In the field of speech and audio technology, Sony has been at the forefront of research and development, leveraging advanced algorithms and cutting-edge hardware to enhance user experiences. Join us in shaping the future of speech recognition and contribute to Sony's legacy of excellence.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "sony",
                "linkedin" => "sony",
                "twitter" => "sony",
                "website" => "https://sony.com",
                "avatar" => "sony.svg",
                "slug" => "sony",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 11,
                "name" => "American Express",
                "email" => "contact@american-express.com",
                "phone" => "+49 152 89674321",
                "description" => "American Express is a globally recognized financial services company with a rich history spanning over 160 years. As one of the largest credit card issuers in the world, we are committed to providing exceptional customer experiences and driving innovation in the industry. Our mission is to become the world's most respected service brand, and we achieve this by fostering a diverse and inclusive culture that values integrity, collaboration, and continuous learning. Join our team and contribute to shaping the future of marketing strategies while impacting millions of customers worldwide.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "american-express",
                "linkedin" => "american-express",
                "twitter" => "american-express",
                "website" => "https://american-express.com",
                "avatar" => "american-express.svg",
                "slug" => "american-express",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 12,
                "name" => "General Motors",
                "email" => "contact@general-motors.com",
                "phone" => "+49 152 89674321",
                "description" => "General Motors is a leading global automotive company that designs, builds, and sells vehicles under the Chevrolet, Cadillac, Buick, and GMC brands. With a rich history of innovation and commitment to excellence, General Motors is at the forefront of automotive technology and sustainability. Join our team and be a part of shaping the future of mobility.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "general-motors",
                "linkedin" => "general-motors",
                "twitter" => "general-motors",
                "website" => "https://general-motors.com",
                "avatar" => "general-motors.svg",
                "slug" => "general-motors",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 13,
                "name" => "Cisco",
                "email" => "contact@cisco.com",
                "phone" => "+49 152 89674321",
                "description" => "Cisco is a global technology leader that specializes in networking and communication solutions. We empower organizations of all sizes to connect, collaborate, and innovate in a digitally connected world. With a strong emphasis on security, our Information Security team is dedicated to protecting our customers' networks, data, and infrastructure from cyber threats. As a company committed to diversity, inclusion, and sustainability, we foster an environment that values creativity, teamwork, and continuous learning.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "cisco",
                "linkedin" => "cisco",
                "twitter" => "cisco",
                "website" => "https://cisco.com",
                "avatar" => "cisco.svg",
                "slug" => "cisco",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 14,
                "name" => "American International Group",
                "email" => "contact@aig.com",
                "phone" => "+49 152 89674321",
                "description" => "American International Group (AIG) is a leading global insurance organization with a presence in more than 80 countries. We provide a wide range of property casualty insurance, life insurance, retirement products, and other financial services to businesses and individuals. At AIG, we believe in fostering a diverse and inclusive work environment where employees can thrive and contribute to the collective success of the organization. Join our team and be part of an organization that is shaping the future of insurance.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "aig",
                "linkedin" => "aig",
                "twitter" => "aig",
                "website" => "https://aig.com",
                "avatar" => "aig.svg",
                "slug" => "aig",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 15,
                "name" => "Ford Motor Company",
                "email" => "contact@ford.com",
                "phone" => "+49 152 89674321",
                "description" => "Ford Motor Company is a globally recognized leader in the automotive industry. Established in 1903, Ford has a rich heritage of innovation and excellence. Our mission is to deliver high-quality vehicles that meet the evolving needs and desires of our customers. As an employee at Ford, you will become part of a dynamic and diverse team committed to driving innovation and shaping the future of mobility. We offer a collaborative work environment, competitive compensation, and comprehensive benefits package.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "ford",
                "linkedin" => "ford",
                "twitter" => "ford",
                "website" => "https://ford.com",
                "avatar" => "ford.svg",
                "slug" => "ford",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 16,
                "name" => "AstraZeneca",
                "email" => "contact@astrazeneca.com",
                "phone" => "+49 152 89674321",
                "description" => "AstraZeneca is a leading global biopharmaceutical company focused on the discovery, development, and commercialization of innovative medicines. With a commitment to improving global health, we strive to deliver life-changing treatments to patients worldwide. Our dedicated team of professionals works collaboratively to drive scientific advancements and make a meaningful impact on patients' lives. Join us in our mission to push the boundaries of science and transform healthcare.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "astrazeneca",
                "linkedin" => "astrazeneca",
                "twitter" => "astrazeneca",
                "website" => "https://astrazeneca.com",
                "avatar" => "astrazeneca.svg",
                "slug" => "astrazeneca",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 17,
                "name" => "Airbus",
                "email" => "contact@airbus.com",
                "phone" => "+49 152 89674321",
                "description" => "Airbus is a global leader in the aerospace industry, designing, manufacturing, and delivering cutting-edge aircraft and related technologies. With a strong commitment to innovation and sustainability, we strive to push the boundaries of what's possible. Joining Airbus means being part of a diverse and talented team that tackles unique challenges and makes a positive impact on the world. We value collaboration, excellence, and a passion for pushing limits.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "airbus",
                "linkedin" => "airbus",
                "twitter" => "airbus",
                "website" => "https://airbus.com",
                "avatar" => "airbus.svg",
                "slug" => "airbus",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 18,
                "name" => "Qualcomm",
                "email" => "contact@qualcomm.com",
                "phone" => "+49 152 89674321",
                "description" => "Qualcomm is a global leader in the development and delivery of innovative digital communication technologies. With a diverse portfolio of products and solutions spanning mobile, automotive, Internet of Things (IoT), and more, Qualcomm is driving the digital transformation and shaping the future of connected devices. As a part of the Qualcomm team, you will have the opportunity to work on groundbreaking technologies and contribute to the development of cutting-edge products that revolutionize industries worldwide.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "qualcomm",
                "linkedin" => "qualcomm",
                "twitter" => "qualcomm",
                "website" => "https://qualcomm.com",
                "avatar" => "qualcomm.svg",
                "slug" => "qualcomm",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 19,
                "name" => "Deutsche Bank AG",
                "email" => "contact@deutsche-bank.com",
                "phone" => "+49 152 89674321",
                "description" => "Deutsche Bank is a leading global financial institution that offers a wide range of banking and financial services to individuals, corporations, and institutional clients. With a strong presence in over 60 countries, we are committed to delivering excellence in everything we do. Our mission is to help our clients achieve their financial goals through innovative and reliable solutions. As a member of our team, you will have the opportunity to work in a collaborative and diverse environment where your skills and expertise will be valued and rewarded.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "deutsche-bank",
                "linkedin" => "deutsche-bank",
                "twitter" => "deutsche-bank",
                "website" => "https://deutsche-bank.com",
                "avatar" => "deutsche-bank.svg",
                "slug" => "deutsche-bank",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 20,
                "name" => "Nike",
                "email" => "contact@nike.com",
                "phone" => "+49 152 89674321",
                "description" => "Nike is a leading global athletic footwear and apparel company. Our mission is to bring inspiration and innovation to every athlete in the world. At Nike, we believe that sports have the power to unleash human potential, whether on the field, the court, or in everyday life. As a Store Associate, you will join a team that shares this passion and works together to provide our customers with exceptional experiences and empower them to achieve their fitness goals.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "nike",
                "linkedin" => "nike",
                "twitter" => "nike",
                "website" => "https://nike.com",
                "avatar" => "nike.svg",
                "slug" => "nike",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 21,
                "name" => "Dell Technologies",
                "email" => "contact@dell-technologies.com",
                "phone" => "+49 152 89674321",
                "description" => "Dell Technologies is a global leader in technology solutions, providing a wide range of products and services to help individuals and organizations achieve their goals. We believe in the power of technology to drive human progress and are committed to delivering innovative solutions that enable our customers to transform their businesses. With a strong focus on sustainability and social responsibility, we strive to make a positive impact on the world through our products, operations, and relationships.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "dell-technologies",
                "linkedin" => "dell-technologies",
                "twitter" => "dell-technologies",
                "website" => "https://dell-technologies.com",
                "avatar" => "dell-technologies.svg",
                "slug" => "dell-technologies",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 22,
                "name" => "Vodafone Group",
                "email" => "contact@vodafone.com",
                "phone" => "+49 152 89674321",
                "description" => "Vodafone is a leading global telecommunications company dedicated to connecting people and businesses. With a presence in over 50 countries, we provide a wide range of innovative products and services that empower individuals and enterprises to communicate and collaborate effectively. Our mission is to enrich people's lives through our advanced mobile and fixed-line networks, unified communications solutions, IoT platforms, and digital services. As a company that values diversity, inclusivity, and sustainability, we are committed to driving positive change in the communities we serve.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "vodafone",
                "linkedin" => "vodafone",
                "twitter" => "vodafone",
                "website" => "https://vodafone.com",
                "avatar" => "vodafone.svg",
                "slug" => "vodafone",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 23,
                "name" => "Volvo Cars",
                "email" => "contact@volvo.com",
                "phone" => "+49 152 89674321",
                "description" => "Volvo Cars is a leading automotive manufacturer dedicated to shaping the future of mobility with sustainable and innovative solutions. We are committed to offering high-quality, safe, and environmentally friendly vehicles to customers worldwide. Our team of passionate and dedicated professionals strives for excellence in all aspects of automotive design, engineering, and manufacturing. Join us and contribute to our mission of creating a sustainable future for both our customers and the planet.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "volvo",
                "linkedin" => "volvo",
                "twitter" => "volvo",
                "website" => "https://volvo.com",
                "avatar" => "volvo.svg",
                "slug" => "volvo",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 24,
                "name" => "Nvidia",
                "email" => "contact@nvidia.com",
                "phone" => "+49 152 89674321",
                "description" => "Nvidia is a global technology company focused on visual computing. With our GPU-accelerated computing platform, we are driving the AI revolution and enabling breakthroughs in deep learning, self-driving cars, gaming, virtual reality, and more. Our diverse and talented team is passionate about pushing the boundaries of what's possible, and we are dedicated to fostering a collaborative and innovative work environment. Join us at Nvidia and be a part of revolutionizing industries with the power of AI.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "nvidia",
                "linkedin" => "nvidia",
                "twitter" => "nvidia",
                "website" => "https://nvidia.com",
                "avatar" => "nvidia.svg",
                "slug" => "nvidia",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 25,
                "name" => "HP",
                "email" => "contact@hp.com",
                "phone" => "+49 152 89674321",
                "description" => "HP is a global technology company that strives to create meaningful innovations. We design and manufacture a wide range of products, including laptops, printers, desktop computers, and 3D printers. With a strong focus on sustainability, diversity, and inclusion, we aim to create positive impact through driving advancements in technology. Join our talented team of engineers, designers, and innovators to revolutionize the way the world works, lives, and plays.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "hp",
                "linkedin" => "hp",
                "twitter" => "hp",
                "website" => "https://hp.com",
                "avatar" => "hp.svg",
                "slug" => "hp",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 26,
                "name" => "Adobe",
                "email" => "contact@adobe.com",
                "phone" => "+49 152 89674321",
                "description" => "Adobe is a leading technology company renowned for its creative software solutions. Our mission is to change the world through digital experiences. We empower individuals and businesses to create and deliver captivating content across multiple platforms, providing them with the tools they need to express their ideas and tell their stories. As an Experience Designer at Adobe, you will be part of a passionate and talented team dedicated to transforming the way people engage with technology and unleash their creativity.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "adobe",
                "linkedin" => "adobe",
                "twitter" => "adobe",
                "website" => "https://adobe.com",
                "avatar" => "adobe.svg",
                "slug" => "adobe",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 27,
                "name" => "Nokia",
                "email" => "contact@nokia.com",
                "phone" => "+49 152 89674321",
                "description" => "Nokia is a global leader in the telecommunications industry, delivering cutting-edge network infrastructure, software solutions, and technology services to customers worldwide. Our ongoing commitment to innovation and technological advancements has made us a trusted partner for network operators, enterprises, and governments across the globe. As a company, we value diversity, collaboration, and excellence in everything we do. Join us and be part of shaping the future of connectivity.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "nokia",
                "linkedin" => "nokia",
                "twitter" => "nokia",
                "website" => "https://nokia.com",
                "avatar" => "nokia.svg",
                "slug" => "nokia",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 28,
                "name" => "AT&T",
                "email" => "contact@at&t.com",
                "phone" => "+49 152 89674321",
                "description" => "AT&T is a leading telecommunications company providing mobile, broadband, and entertainment services to millions of customers worldwide. We strive to deliver innovative solutions and drive technological advancements in the industry. With a history spanning over a century, AT&T has established itself as a trusted name in communication technology. Join our team and contribute to shaping the future of telecommunications.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "at&t",
                "linkedin" => "at&t",
                "twitter" => "at&t",
                "website" => "https://at&t.com",
                "avatar" => "at&t.svg",
                "slug" => "at&t",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 29,
                "name" => "Intel",
                "email" => "contact@intel.com",
                "phone" => "+49 152 89674321",
                "description" => "Intel is a global technology leader, powering the data-centric world with its innovative products and solutions. We design and manufacture advanced processors, SoCs, and other semiconductor devices that enable the digital transformation across various industries. Our commitment to innovation and collaboration drives our success in delivering cutting-edge technologies that reshape the future of computing and communications. Join us in our mission to create a smart and connected world through groundbreaking silicon solutions.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "intel",
                "linkedin" => "intel",
                "twitter" => "intel",
                "website" => "https://intel.com",
                "avatar" => "intel.svg",
                "slug" => "intel",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ],
            [
                "id" => 30,
                "name" => "Boeing Co",
                "email" => "contact@boeing.com",
                "phone" => "+49 152 89674321",
                "description" => "Boeing is the world's largest aerospace company and leading manufacturer of commercial jetliners, defense, space, and security systems. With a legacy spanning over a century, we are committed to delivering safe, efficient, and innovative solutions that redefine the future of air and space transportation.",
                "address" => "34 Karl-Marx-Allee",
                "facebook" => "boeing",
                "linkedin" => "boeing",
                "twitter" => "boeing",
                "website" => "https://boeing.com",
                "avatar" => "boeing.svg",
                "slug" => "boeing",
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10"
            ]
        ]);
    }
}
