<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // User Model
        $userPermission1 = Permission::create(['name' => "list: user"]);
        $userPermission2 = Permission::create(['name' => "read: user"]);
        $userPermission3 = Permission::create(['name' => "update: user"]);
        $userPermission4 = Permission::create(['name' => "delete: user"]);

        // Recruiter Model
        $recruiterPermission1 = Permission::create(['name' => "read: recruiter"]);
        $recruiterPermission2 = Permission::create(['name' => "update: recruiter"]);

        // Applicant Model
        $applicantPermission1 = Permission::create(['name' => "read: applicant"]);
        $applicantPermission2 = Permission::create(['name' => "update: applicant"]);

        // Company Model
        $companyPermission1 = Permission::create(['name' => "list: company"]);
        $companyPermission2 = Permission::create(['name' => "create: company"]);
        $companyPermission3 = Permission::create(['name' => "read: company"]);
        $companyPermission4 = Permission::create(['name' => "update: company"]);
        $companyPermission5 = Permission::create(['name' => "delete: company"]);

        // Job Model
        $jobPermission1 = Permission::create(['name' => "list: job"]);
        $jobPermission2 = Permission::create(['name' => "create: job"]);
        $jobPermission3 = Permission::create(['name' => "read: job"]);
        $jobPermission4 = Permission::create(['name' => "update: job"]);
        $jobPermission5 = Permission::create(['name' => "delete: job"]);

        // Role Model
        $rolePermission1 = Permission::create(['name' => "list: role"]);
        $rolePermission2 = Permission::create(['name' => "create: role"]);
        $rolePermission3 = Permission::create(['name' => "read: role"]);
        $rolePermission4 = Permission::create(['name' => "update: role"]);
        $rolePermission5 = Permission::create(['name' => "delete: role"]);

        // Permission Model
        $permission1 = Permission::create(['name' => "list: permission"]);
        $permission2 = Permission::create(['name' => "create: permission"]);
        $permission3 = Permission::create(['name' => "read: permission"]);
        $permission4 = Permission::create(['name' => "update: permission"]);
        $permission5 = Permission::create(['name' => "delete: permission"]);

        $adminRole = Role::create(['name' => "admin"])->syncPermissions([
            $userPermission1,
            $userPermission2,
            $userPermission3,
            $userPermission4,
            $recruiterPermission1,
            $recruiterPermission2,
            $applicantPermission1,
            $applicantPermission2,
            $companyPermission1,
            $companyPermission2,
            $companyPermission3,
            $companyPermission4,
            $companyPermission5,
            $jobPermission1,
            $jobPermission3,
            $jobPermission5,
            $rolePermission1,
            $rolePermission2,
            $rolePermission3,
            $rolePermission4,
            $rolePermission5,
            $permission1,
            $permission2,
            $permission3,
            $permission4,
            $permission5,
        ]);

        $recruiterRole = Role::create(['name' => "recruiter"])->syncPermissions([
            $userPermission2,
            $userPermission3,
            $userPermission4,
            $recruiterPermission1,
            $recruiterPermission2,
            $companyPermission1,
            $companyPermission3,
            $companyPermission4,
            $jobPermission1,
            $jobPermission2,
            $jobPermission3,
            $jobPermission4,
            $jobPermission5,
        ]);

        $applicantRole = Role::create(['name' => "applicant"])->syncPermissions([
            $userPermission2,
            $userPermission3,
            $userPermission4,
            $recruiterPermission1,
            $companyPermission1,
            $companyPermission3,
            $jobPermission1,
            $jobPermission3,
        ]);

        $users = [
            [
                "id" => 0,
                "name" => "Robert Brown",
                "role" => "admin",
                "email" => "robertbrown@jobquery.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("robertbrown"),
                "phone" => "0454 512343",
                "linkedin_profile" => "robertbrown",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "robertbrown.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 2
            ],
            [
                "id" => 1,
                "name" => "Jane Doe",
                "role" => "recruiter",
                "email" => "janedoe@innovize.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("janedoe"),
                "phone" => "0454 512343",
                "linkedin_profile" => "janedoe",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "janedoe.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 2
            ],
            [
                "id" => 2,
                "name" => "Emily Brown",
                "role" => "recruiter",
                "email" => "emilybrown@innovize.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("emilybrown"),
                "phone" => "0159 203948",
                "linkedin_profile" => "emilybrown",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "emilybrown.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 0
            ],
            [
                "id" => 3,
                "name" => "Michael Wilson",
                "role" => "recruiter",
                "email" => "michaelwilson@samsung.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("michaelwilson"),
                "phone" => "0172 203948",
                "linkedin_profile" => "michaelwilson",
                "language" => "fr",
                "timezone" => "Europe/Paris",
                "mfa" => false,
                "avatar" => "michaelwilson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 1
            ],
            [
                "id" => 4,
                "name" => "Sara Brown",
                "role" => "recruiter",
                "email" => "sarabrown@samsung.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("sarabrown"),
                "phone" => "0166 203948",
                "linkedin_profile" => "sarabrown",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "sarabrown.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 2

            ],
            [
                "id" => 5,
                "name" => "Lucas Martin",
                "role" => "recruiter",
                "email" => "lucasmartin@tesla.com",
                "email_verified_at" => "2023-02-14",
                "password" => Hash::make("lucasmartin"),
                "phone" => "0177 234567",
                "linkedin_profile" => "lucasmartin",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "lucasmartin.png",
                "remember_token" => Str::random(10),
                "created_at" => "2023-02-14",
                "updated_at" => "2023-02-14",
                "location_id" => 3
            ],
            [
                "id" => 6,
                "name" => "Isabella Turner",
                "role" => "recruiter",
                "email" => "isabellaturner@tesla.com",
                "email_verified_at" => "2023-03-21",
                "password" => Hash::make("isabellaturner"),
                "phone" => "0177 345678",
                "linkedin_profile" => "isabellaturner",
                "language" => "fr",
                "timezone" => "Europe/Madrid",
                "mfa" => true,
                "avatar" => "isabellaturner.png",
                "remember_token" => Str::random(10),
                "created_at" => "2023-03-21",
                "updated_at" => "2023-03-21",
                "location_id" => 5
            ],
            [
                "id" => 7,
                "name" => "Henry Adams",
                "role" => "recruiter",
                "email" => "henryadams@spotify.com",
                "email_verified_at" => "2023-04-18",
                "password" => Hash::make("henryadams"),
                "phone" => "0177 456789",
                "linkedin_profile" => "henryadams",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "henryadams.png",
                "remember_token" => Str::random(10),
                "created_at" => "2023-04-18",
                "updated_at" => "2023-04-18",
                "location_id" => 0
            ],
            [
                "id" => 8,
                "name" => "Natalie Collins",
                "role" => "recruiter",
                "email" => "nataliecollins@spotify.com",
                "email_verified_at" => "2023-05-30",
                "password" => Hash::make("nataliecollins"),
                "phone" => "0177 567890",
                "linkedin_profile" => "nataliecollins",
                "language" => "de",
                "timezone" => "Europe/Rome",
                "mfa" => true,
                "avatar" => "nataliecollins.png",
                "remember_token" => Str::random(10),
                "created_at" => "2023-05-30",
                "updated_at" => "2023-05-30",
                "location_id" => 4
            ],
            [
                "id" => 9,
                "name" => "Ethan Walker",
                "role" => "recruiter",
                "email" => "ethanwalker@ibm.com",
                "email_verified_at" => "2023-06-15",
                "password" => Hash::make("ethanwalker"),
                "phone" => "0177 678901",
                "linkedin_profile" => "ethanwalker",
                "language" => "fr",
                "timezone" => "Europe/Lisbon",
                "mfa" => false,
                "avatar" => "ethanwalker.png",
                "remember_token" => Str::random(10),
                "created_at" => "2023-06-15",
                "updated_at" => "2023-06-15",
                "location_id" => 6
            ],
            [
                "id" => 10,
                "name" => "Ava Mitchell",
                "role" => "recruiter",
                "email" => "avamitchell@ibm.com",
                "email_verified_at" => "2023-07-10",
                "password" => Hash::make("avamitchell"),
                "phone" => "0177 789012",
                "linkedin_profile" => "avamitchell",
                "language" => "de",
                "timezone" => "Europe/Amsterdam",
                "mfa" => true,
                "avatar" => "avamitchell.png",
                "remember_token" => Str::random(10),
                "created_at" => "2023-07-10",
                "updated_at" => "2023-07-10",
                "location_id" => 7
            ],
            [
                "id" => 11,
                "name" => "Owen Scott",
                "role" => "recruiter",
                "email" => "owenscott@sap.com",
                "email_verified_at" => "2023-08-20",
                "password" => Hash::make("owenscott"),
                "phone" => "0177 890123",
                "linkedin_profile" => "owenscott",
                "language" => "de",
                "timezone" => "Europe/Stockholm",
                "mfa" => false,
                "avatar" => "owenscott.png",
                "remember_token" => Str::random(10),
                "created_at" => "2023-08-20",
                "updated_at" => "2023-08-20",
                "location_id" => 8
            ],
            [
                "id" => 12,
                "name" => "Mia Peterson",
                "role" => "recruiter",
                "email" => "miapeterson@sap.com",
                "email_verified_at" => "2023-09-05",
                "password" => Hash::make("miapeterson"),
                "phone" => "0177 901234",
                "linkedin_profile" => "miapeterson",
                "language" => "en-US",
                "timezone" => "Europe/Oslo",
                "mfa" => true,
                "avatar" => "miapeterson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2023-09-05",
                "updated_at" => "2023-09-05",
                "location_id" => 9
            ],
            [
                "id" => 13,
                "name" => "Liam Thompson",
                "role" => "recruiter",
                "email" => "liamthompson@salesforce.com",
                "email_verified_at" => "2023-09-25",
                "password" => Hash::make("liamthompson"),
                "phone" => "0177 012345",
                "linkedin_profile" => "liamthompson",
                "language" => "fr",
                "timezone" => "Europe/Copenhagen",
                "mfa" => false,
                "avatar" => "liamthompson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2023-09-25",
                "updated_at" => "2023-09-25",
                "location_id" => 11
            ],
            [
                "id" => 14,
                "name" => "Sophia Moore",
                "role" => "recruiter",
                "email" => "sophiamoore@salesforce.com",
                "email_verified_at" => "2023-10-01",
                "password" => Hash::make("sophiamoore"),
                "phone" => "0177 123098",
                "linkedin_profile" => "sophiamoore",
                "language" => "de",
                "timezone" => "Europe/Helsinki",
                "mfa" => true,
                "avatar" => "sophiamoore.png",
                "remember_token" => Str::random(10),
                "created_at" => "2023-10-01",
                "updated_at" => "2023-10-01",
                "location_id" => 12
            ],
            [
                "id" => 15,
                "name" => "Zara Blake",
                "role" => "recruiter",
                "email" => "zarablake@jpmorgan-chase.com",
                "email_verified_at" => "2024-01-15",
                "password" => Hash::make("zarablake"),
                "phone" => "0177 234890",
                "linkedin_profile" => "zarablake",
                "language" => "fr",
                "timezone" => "Europe/Moscow",
                "mfa" => false,
                "avatar" => "zarablake.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-01-15",
                "updated_at" => "2024-01-15",
                "location_id" => 12
            ],
            [
                "id" => 16,
                "name" => "Aiden Carter",
                "role" => "recruiter",
                "email" => "aidencarter@jpmorgan-chase.com",
                "email_verified_at" => "2024-02-10",
                "password" => Hash::make("aidencarter"),
                "phone" => "0177 345901",
                "linkedin_profile" => "aidencarter",
                "language" => "de",
                "timezone" => "Europe/Warsaw",
                "mfa" => true,
                "avatar" => "aidencarter.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-02-10",
                "updated_at" => "2024-02-10",
                "location_id" => 13
            ],
            [
                "id" => 17,
                "name" => "Chloe Morris",
                "role" => "recruiter",
                "email" => "chloemorris@pfizer.com",
                "email_verified_at" => "2024-03-01",
                "password" => Hash::make("chloemorris"),
                "phone" => "0177 456012",
                "linkedin_profile" => "chloemorris",
                "language" => "en-US",
                "timezone" => "Europe/Athens",
                "mfa" => false,
                "avatar" => "chloemorris.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-03-01",
                "updated_at" => "2024-03-01",
                "location_id" => 14
            ],
            [
                "id" => 18,
                "name" => "Benjamin Reed",
                "role" => "recruiter",
                "email" => "benjaminreed@pfizer.com",
                "email_verified_at" => "2024-03-22",
                "password" => Hash::make("benjaminreed"),
                "phone" => "0177 567123",
                "linkedin_profile" => "benjaminreed",
                "language" => "en-US",
                "timezone" => "Europe/Istanbul",
                "mfa" => true,
                "avatar" => "benjaminreed.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-03-22",
                "updated_at" => "2024-03-22",
                "location_id" => 15
            ],
            [
                "id" => 19,
                "name" => "Sophie Müller",
                "role" => "recruiter",
                "email" => "sophie.muller@johnson&johnson.com",
                "email_verified_at" => "2024-04-10",
                "password" => Hash::make("sophiemuller"),
                "phone" => "+49 170 1234567",
                "linkedin_profile" => "sophie-muller",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "sophiemuller.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-04-10",
                "updated_at" => "2024-04-10",
                "location_id" => 0
            ],
            [
                "id" => 20,
                "name" => "Landon Gray",
                "role" => "recruiter",
                "email" => "landongray@johnson&johnson.com",
                "email_verified_at" => "2024-05-05",
                "password" => Hash::make("landongray"),
                "phone" => "0177 789345",
                "linkedin_profile" => "landongray",
                "language" => "en-US",
                "timezone" => "Europe/Budapest",
                "mfa" => true,
                "avatar" => "landongray.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-05-05",
                "updated_at" => "2024-05-05",
                "location_id" => 16
            ],
            [
                "id" => 21,
                "name" => "Eleanor White",
                "role" => "recruiter",
                "email" => "eleanorwhite@sony.com",
                "email_verified_at" => "2024-06-15",
                "password" => Hash::make("eleanorwhite"),
                "phone" => "0177 890456",
                "linkedin_profile" => "eleanorwhite",
                "language" => "de",
                "timezone" => "Europe/Prague",
                "mfa" => false,
                "avatar" => "eleanorwhite.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-06-15",
                "updated_at" => "2024-06-15",
                "location_id" => 17
            ],
            [
                "id" => 22,
                "name" => "Sebastian King",
                "role" => "recruiter",
                "email" => "sebastianking@sony.com",
                "email_verified_at" => "2024-07-20",
                "password" => Hash::make("sebastianking"),
                "phone" => "0177 901567",
                "linkedin_profile" => "sebastianking",
                "language" => "de",
                "timezone" => "Europe/Bratislava",
                "mfa" => true,
                "avatar" => "sebastianking.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-07-20",
                "updated_at" => "2024-07-20",
                "location_id" => 18
            ],
            [
                "id" => 23,
                "name" => "Amelia Foster",
                "role" => "recruiter",
                "email" => "ameliafoster@american-express.com",
                "email_verified_at" => "2024-08-10",
                "password" => Hash::make("ameliafoster"),
                "phone" => "0177 012456",
                "linkedin_profile" => "ameliafoster",
                "language" => "en-US",
                "timezone" => "Europe/Sofia",
                "mfa" => false,
                "avatar" => "ameliafoster.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-08-10",
                "updated_at" => "2024-08-10",
                "location_id" => 19
            ],
            [
                "id" => 24,
                "name" => "Jack Harper",
                "role" => "recruiter",
                "email" => "jackharper@american-express.com",
                "email_verified_at" => "2024-09-05",
                "password" => Hash::make("jackharper"),
                "phone" => "0177 123456",
                "linkedin_profile" => "jackharper",
                "language" => "en-US",
                "timezone" => "Europe/Bucharest",
                "mfa" => true,
                "avatar" => "jackharper.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-09-05",
                "updated_at" => "2024-09-05",
                "location_id" => 20
            ],
            [
                "id" => 25,
                "name" => "Ivy Clarke",
                "role" => "recruiter",
                "email" => "ivyclarke@general-motors.com",
                "email_verified_at" => "2024-10-01",
                "password" => Hash::make("ivyclarke"),
                "phone" => "0177 234567",
                "linkedin_profile" => "ivyclarke",
                "language" => "fr",
                "timezone" => "Europe/Vilnius",
                "mfa" => false,
                "avatar" => "ivyclarke.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-10-01",
                "updated_at" => "2024-10-01",
                "location_id" => 21
            ],
            [
                "id" => 26,
                "name" => "Noah Murphy",
                "role" => "recruiter",
                "email" => "noahmurphy@general-motors.com",
                "email_verified_at" => "2024-10-15",
                "password" => Hash::make("noahmurphy"),
                "phone" => "0177 345678",
                "linkedin_profile" => "noahmurphy",
                "language" => "fr",
                "timezone" => "Europe/Tallinn",
                "mfa" => true,
                "avatar" => "noahmurphy.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-10-15",
                "updated_at" => "2024-10-15",
                "location_id" => 22
            ],
            [
                "id" => 27,
                "name" => "Grace Allen",
                "role" => "recruiter",
                "email" => "graceallen@cisco.com",
                "email_verified_at" => "2024-11-01",
                "password" => Hash::make("graceallen"),
                "phone" => "0177 456789",
                "linkedin_profile" => "graceallen",
                "language" => "fr",
                "timezone" => "Europe/Riga",
                "mfa" => false,
                "avatar" => "graceallen.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-11-01",
                "updated_at" => "2024-11-01",
                "location_id" => 23
            ],
            [
                "id" => 28,
                "name" => "Oliver Martin",
                "role" => "recruiter",
                "email" => "olivermartin@cisco.com",
                "email_verified_at" => "2024-11-10",
                "password" => Hash::make("olivermartin"),
                "phone" => "0177 567890",
                "linkedin_profile" => "olivermartin",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => true,
                "avatar" => "olivermartin.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-11-10",
                "updated_at" => "2024-11-10",
                "location_id" => 2
            ],
            [
                "id" => 29,
                "name" => "Ella Carter",
                "role" => "recruiter",
                "email" => "ellacarter@aig.com",
                "email_verified_at" => "2024-11-20",
                "password" => Hash::make("ellacarter"),
                "phone" => "0177 678901",
                "linkedin_profile" => "ellacarter",
                "language" => "en-US",
                "timezone" => "Europe/Zagreb",
                "mfa" => false,
                "avatar" => "ellacarter.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-11-20",
                "updated_at" => "2024-11-20",
                "location_id" => 24
            ],
            [
                "id" => 30,
                "name" => "Mason Wood",
                "role" => "recruiter",
                "email" => "masonwood@aig.com",
                "email_verified_at" => "2024-12-05",
                "password" => Hash::make("masonwood"),
                "phone" => "0177 789012",
                "linkedin_profile" => "masonwood",
                "language" => "fr",
                "timezone" => "Europe/Ljubljana",
                "mfa" => true,
                "avatar" => "masonwood.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-12-05",
                "updated_at" => "2024-12-05",
                "location_id" => 25
            ],
            [
                "id" => 31,
                "name" => "Lila Hayes",
                "role" => "recruiter",
                "email" => "lilahayes@ford.com",
                "email_verified_at" => "2024-12-15",
                "password" => Hash::make("lilahayes"),
                "phone" => "0177 890123",
                "linkedin_profile" => "lilahayes",
                "language" => "en-US",
                "timezone" => "Europe/Tirane",
                "mfa" => false,
                "avatar" => "lilahayes.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-12-15",
                "updated_at" => "2024-12-15",
                "location_id" => 26
            ],
            [
                "id" => 32,
                "name" => "Eli Hughes",
                "role" => "recruiter",
                "email" => "elihughes@ford.com",
                "email_verified_at" => "2024-12-25",
                "password" => Hash::make("elihughes"),
                "phone" => "0177 901234",
                "linkedin_profile" => "elihughes",
                "language" => "en-US",
                "timezone" => "Europe/Valletta",
                "mfa" => true,
                "avatar" => "elihughes.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-12-25",
                "updated_at" => "2024-12-25",
                "location_id" => 27
            ],
            [
                "id" => 33,
                "name" => "Nina Morris",
                "role" => "recruiter",
                "email" => "ninamorris@astrazeneca.com",
                "email_verified_at" => "2024-01-10",
                "password" => Hash::make("ninamorris"),
                "phone" => "0177 123789",
                "linkedin_profile" => "ninamorris",
                "language" => "fr",
                "timezone" => "Europe/Luxembourg",
                "mfa" => false,
                "avatar" => "ninamorris.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-01-10",
                "updated_at" => "2024-01-10",
                "location_id" => 28
            ],
            [
                "id" => 34,
                "name" => "Oscar Sullivan",
                "role" => "recruiter",
                "email" => "oscarsullivan@astrazeneca.com",
                "email_verified_at" => "2024-01-20",
                "password" => Hash::make("oscarsullivan"),
                "phone" => "0177 234567",
                "linkedin_profile" => "oscarsullivan",
                "language" => "en-US",
                "timezone" => "Europe/Reykjavik",
                "mfa" => true,
                "avatar" => "oscarsullivan.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-01-20",
                "updated_at" => "2024-01-20",
                "location_id" => 29
            ],
            [
                "id" => 35,
                "name" => "Zoe Brooks",
                "role" => "recruiter",
                "email" => "zoebrooks@airbus.com",
                "email_verified_at" => "2024-02-05",
                "password" => Hash::make("zoebrooks"),
                "phone" => "0177 345678",
                "linkedin_profile" => "zoebrooks",
                "language" => "de",
                "timezone" => "Europe/Kyiv",
                "mfa" => false,
                "avatar" => "zoebrooks.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-02-05",
                "updated_at" => "2024-02-05",
                "location_id" => 30
            ],
            [
                "id" => 36,
                "name" => "Leo Bennett",
                "role" => "recruiter",
                "email" => "leobennett@airbus.com",
                "email_verified_at" => "2024-02-20",
                "password" => Hash::make("leobennett"),
                "phone" => "0177 456789",
                "linkedin_profile" => "leobennett",
                "language" => "fr",
                "timezone" => "Europe/Tallinn",
                "mfa" => true,
                "avatar" => "leobennett.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-02-20",
                "updated_at" => "2024-02-20",
                "location_id" => 22
            ],
            [
                "id" => 37,
                "name" => "Sophie Howard",
                "role" => "recruiter",
                "email" => "sophiehoward@qualcomm.com",
                "email_verified_at" => "2024-03-10",
                "password" => Hash::make("sophiehoward"),
                "phone" => "0177 567890",
                "linkedin_profile" => "sophiehoward",
                "language" => "fr",
                "timezone" => "Europe/Vilnius",
                "mfa" => false,
                "avatar" => "sophiehoward.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-03-10",
                "updated_at" => "2024-03-10",
                "location_id" => 21
            ],
            [
                "id" => 38,
                "name" => "Jacob Fisher",
                "role" => "recruiter",
                "email" => "jacobfisher@qualcomm.com",
                "email_verified_at" => "2024-03-25",
                "password" => Hash::make("jacobfisher"),
                "phone" => "0177 678901",
                "linkedin_profile" => "jacobfisher",
                "language" => "de",
                "timezone" => "Europe/Minsk",
                "mfa" => true,
                "avatar" => "jacobfisher.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-03-25",
                "updated_at" => "2024-03-25",
                "location_id" => 31
            ],
            [
                "id" => 39,
                "name" => "Hannah Russell",
                "role" => "recruiter",
                "email" => "hannahrussell@deutsche-bank.com",
                "email_verified_at" => "2024-04-01",
                "password" => Hash::make("hannahrussell"),
                "phone" => "0177 123456",
                "linkedin_profile" => "hannahrussell",
                "language" => "en-US",
                "timezone" => "Europe/Oslo",
                "mfa" => false,
                "avatar" => "hannahrussell.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-04-01",
                "updated_at" => "2024-04-01",
                "location_id" => 9
            ],
            [
                "id" => 40,
                "name" => "Liam Parker",
                "role" => "recruiter",
                "email" => "liamparker@deutsche-bank.com",
                "email_verified_at" => "2024-04-10",
                "password" => Hash::make("liamparker"),
                "phone" => "0177 234567",
                "linkedin_profile" => "liamparker",
                "language" => "de",
                "timezone" => "Europe/Stockholm",
                "mfa" => true,
                "avatar" => "liamparker.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-04-10",
                "updated_at" => "2024-04-10",
                "location_id" => 8
            ],
            [
                "id" => 41,
                "name" => "Mila Sanchez",
                "role" => "recruiter",
                "email" => "milasanchez@nike.com",
                "email_verified_at" => "2024-05-01",
                "password" => Hash::make("milasanchez"),
                "phone" => "0177 345678",
                "linkedin_profile" => "milasanchez",
                "language" => "fr",
                "timezone" => "Europe/Madrid",
                "mfa" => false,
                "avatar" => "milasanchez.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-05-01",
                "updated_at" => "2024-05-01",
                "location_id" => 5
            ],
            [
                "id" => 42,
                "name" => "Evan Brooks",
                "role" => "recruiter",
                "email" => "evanbrooks@nike.com",
                "email_verified_at" => "2024-05-15",
                "password" => Hash::make("evanbrooks"),
                "phone" => "0177 456789",
                "linkedin_profile" => "evanbrooks",
                "language" => "de",
                "timezone" => "Europe/Helsinki",
                "mfa" => true,
                "avatar" => "evanbrooks.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-05-15",
                "updated_at" => "2024-05-15",
                "location_id" => 11
            ],
            [
                "id" => 43,
                "name" => "Nora Young",
                "role" => "recruiter",
                "email" => "norayoung@dell-technologies.com",
                "email_verified_at" => "2024-06-01",
                "password" => Hash::make("norayoung"),
                "phone" => "0177 567890",
                "linkedin_profile" => "norayoung",
                "language" => "en-US",
                "timezone" => "Europe/Reykjavik",
                "mfa" => false,
                "avatar" => "norayoung.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-06-01",
                "updated_at" => "2024-06-01",
                "location_id" => 29
            ],
            [
                "id" => 44,
                "name" => "Avery Campbell",
                "role" => "recruiter",
                "email" => "averycampbell@dell-technologies.com",
                "email_verified_at" => "2024-06-15",
                "password" => Hash::make("averycampbell"),
                "phone" => "0177 678901",
                "linkedin_profile" => "averycampbell",
                "language" => "fr",
                "timezone" => "Europe/Tallinn",
                "mfa" => true,
                "avatar" => "averycampbell.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-06-15",
                "updated_at" => "2024-06-15",
                "location_id" => 22
            ],
            [
                "id" => 45,
                "name" => "Henry Ward",
                "role" => "recruiter",
                "email" => "henryward@vodafone.com",
                "email_verified_at" => "2024-07-01",
                "password" => Hash::make("henryward"),
                "phone" => "0177 789012",
                "linkedin_profile" => "henryward",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "henryward.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-07-01",
                "updated_at" => "2024-07-01",
                "location_id" => 2
            ],
            [
                "id" => 46,
                "name" => "Lydia Hayes",
                "role" => "recruiter",
                "email" => "lydiahayes@vodafone.com",
                "email_verified_at" => "2024-07-15",
                "password" => Hash::make("lydiahayes"),
                "phone" => "0177 890123",
                "linkedin_profile" => "lydiahayes",
                "language" => "fr",
                "timezone" => "Europe/Sarajevo",
                "mfa" => true,
                "avatar" => "lydiahayes.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-07-15",
                "updated_at" => "2024-07-15",
                "location_id" => 32
            ],
            [
                "id" => 47,
                "name" => "Isaac Ross",
                "role" => "recruiter",
                "email" => "isaacross@volvo.com",
                "email_verified_at" => "2024-08-01",
                "password" => Hash::make("isaacross"),
                "phone" => "0177 901234",
                "linkedin_profile" => "isaacross",
                "language" => "en-US",
                "timezone" => "Europe/Zagreb",
                "mfa" => false,
                "avatar" => "isaacross.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-08-01",
                "updated_at" => "2024-08-01",
                "location_id" => 24
            ],
            [
                "id" => 48,
                "name" => "Sienna Cook",
                "role" => "recruiter",
                "email" => "siennacook@volvo.com",
                "email_verified_at" => "2024-08-15",
                "password" => Hash::make("siennacook"),
                "phone" => "0177 012345",
                "linkedin_profile" => "siennacook",
                "language" => "en-US",
                "timezone" => "Europe/Tirane",
                "mfa" => true,
                "avatar" => "siennacook.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-08-15",
                "updated_at" => "2024-08-15",
                "location_id" => 26
            ],
            [
                "id" => 49,
                "name" => "Luca Rossi",
                "role" => "recruiter",
                "email" => "luca.rossi@nvidia.com",
                "email_verified_at" => "2024-04-10",
                "password" => Hash::make("lucarossi"),
                "phone" => "+39 345 6789012",
                "linkedin_profile" => "luca-rossi",
                "language" => "de",
                "timezone" => "Europe/Rome",
                "mfa" => false,
                "avatar" => "lucarossi.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-04-10",
                "updated_at" => "2024-04-10",
                "location_id" => 4
            ],
            [
                "id" => 50,
                "name" => "Anna Johansson",
                "role" => "recruiter",
                "email" => "anna.johansson@nvidia.com",
                "email_verified_at" => "2024-04-10",
                "password" => Hash::make("annajohansson"),
                "phone" => "+46 70 1234567",
                "linkedin_profile" => "anna-johansson",
                "language" => "de",
                "timezone" => "Europe/Stockholm",
                "mfa" => false,
                "avatar" => "annajohansson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-04-10",
                "updated_at" => "2024-04-10",
                "location_id" => 8
            ],
            [
                "id" => 51,
                "name" => "Chloe Adams",
                "role" => "recruiter",
                "email" => "chloeadams@hp.com",
                "email_verified_at" => "2024-10-01",
                "password" => Hash::make("chloeadams"),
                "phone" => "0177 345678",
                "linkedin_profile" => "chloeadams",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "chloeadams.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-10-01",
                "updated_at" => "2024-10-01",
                "location_id" => 0
            ],
            [
                "id" => 52,
                "name" => "Ethan Adams",
                "role" => "recruiter",
                "email" => "ethanadams@hp.com",
                "email_verified_at" => "2024-10-10",
                "password" => Hash::make("ethanadams"),
                "phone" => "0177 456789",
                "linkedin_profile" => "ethanadams",
                "language" => "de",
                "timezone" => "Europe/Amsterdam",
                "mfa" => true,
                "avatar" => "ethanadams.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-10-10",
                "updated_at" => "2024-10-10",
                "location_id" => 7
            ],
            [
                "id" => 53,
                "name" => "Olivia Murphy",
                "role" => "recruiter",
                "email" => "oliviamurphy@adobe.com",
                "email_verified_at" => "2024-10-20",
                "password" => Hash::make("oliviamurphy"),
                "phone" => "0177 567890",
                "linkedin_profile" => "oliviamurphy",
                "language" => "fr",
                "timezone" => "Europe/Copenhagen",
                "mfa" => false,
                "avatar" => "oliviamurphy.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-10-20",
                "updated_at" => "2024-10-20",
                "location_id" => 10
            ],
            [
                "id" => 54,
                "name" => "Noah Walker",
                "role" => "recruiter",
                "email" => "noahwalker@adobe.com",
                "email_verified_at" => "2024-11-01",
                "password" => Hash::make("noahwalker"),
                "phone" => "0177 678901",
                "linkedin_profile" => "noahwalker",
                "language" => "en-US",
                "timezone" => "Europe/Budapest",
                "mfa" => true,
                "avatar" => "noahwalker.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-11-01",
                "updated_at" => "2024-11-01",
                "location_id" => 16
            ],
            [
                "id" => 55,
                "name" => "Emma Foster",
                "role" => "recruiter",
                "email" => "emmafoster@nokia.com",
                "email_verified_at" => "2024-11-10",
                "password" => Hash::make("emmafoster"),
                "phone" => "0177 789012",
                "linkedin_profile" => "emmafoster",
                "language" => "de",
                "timezone" => "Europe/Warsaw",
                "mfa" => false,
                "avatar" => "emmafoster.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-11-10",
                "updated_at" => "2024-11-10",
                "location_id" => 13
            ],
            [
                "id" => 56,
                "name" => "Logan Perry",
                "role" => "recruiter",
                "email" => "loganperry@nokia.com",
                "email_verified_at" => "2024-11-20",
                "password" => Hash::make("loganperry"),
                "phone" => "0177 890123",
                "linkedin_profile" => "loganperry",
                "language" => "fr",
                "timezone" => "Europe/Vilnius",
                "mfa" => true,
                "avatar" => "loganperry.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-11-20",
                "updated_at" => "2024-11-20",
                "location_id" => 21
            ],
            [
                "id" => 57,
                "name" => "Zara Morgan",
                "role" => "recruiter",
                "email" => "zaramorgan@at&t.com",
                "email_verified_at" => "2024-12-01",
                "password" => Hash::make("zaramorgan"),
                "phone" => "0177 901234",
                "linkedin_profile" => "zaramorgan",
                "language" => "de",
                "timezone" => "Europe/Bratislava",
                "mfa" => false,
                "avatar" => "zaramorgan.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-12-01",
                "updated_at" => "2024-12-01",
                "location_id" => 18
            ],
            [
                "id" => 58,
                "name" => "Oliver Collins",
                "role" => "recruiter",
                "email" => "olivercollins@at&t.com",
                "email_verified_at" => "2024-12-10",
                "password" => Hash::make("olivercollins"),
                "phone" => "0177 012345",
                "linkedin_profile" => "olivercollins",
                "language" => "fr",
                "timezone" => "Europe/Riga",
                "mfa" => true,
                "avatar" => "olivercollins.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-12-10",
                "updated_at" => "2024-12-10",
                "location_id" => 23
            ],
            [
                "id" => 59,
                "name" => "Aiden Taylor",
                "role" => "recruiter",
                "email" => "aidentaylor@intel.com",
                "email_verified_at" => "2024-12-20",
                "password" => Hash::make("aidentaylor"),
                "phone" => "0177 123456",
                "linkedin_profile" => "aidentaylor",
                "language" => "fr",
                "timezone" => "Europe/Tallinn",
                "mfa" => false,
                "avatar" => "aidentaylor.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-12-20",
                "updated_at" => "2024-12-20",
                "location_id" => 22
            ],
            [
                "id" => 60,
                "name" => "Élisabeth Dubois",
                "role" => "recruiter",
                "email" => "elisabeth.dubois@intel.com",
                "email_verified_at" => "2024-04-10",
                "password" => Hash::make("elisabethdubois"),
                "phone" => "+33 6 12 34 56 78",
                "linkedin_profile" => "elisabeth-dubois",
                "language" => "fr",
                "timezone" => "Europe/Paris",
                "mfa" => false,
                "avatar" => "elisabethdubois.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-04-10",
                "updated_at" => "2024-04-10",
                "location_id" => 1
            ],
            [
                "id" => 61,
                "name" => "Jürgen Schmidt",
                "role" => "recruiter",
                "email" => "juergen.schmidt@boeing.com",
                "email_verified_at" => "2024-04-10",
                "password" => Hash::make("juergenschmidt"),
                "phone" => "+49 170 9876543",
                "linkedin_profile" => "juergen-schmidt",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "jurgenschmidt.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-04-10",
                "updated_at" => "2024-04-10",
                "location_id" => 0
            ],
            [
                "id" => 62,
                "name" => "Isabella García",
                "role" => "recruiter",
                "email" => "isabella.garcia@boeing.com",
                "email_verified_at" => "2024-04-10",
                "password" => Hash::make("isabellagarcia"),
                "phone" => "+34 612 345 678",
                "linkedin_profile" => "isabella-garcia",
                "language" => "fr",
                "timezone" => "Europe/Madrid",
                "mfa" => false,
                "avatar" => "isabellagarcia.png",
                "remember_token" => Str::random(10),
                "created_at" => "2024-04-10",
                "updated_at" => "2024-04-10",
                "location_id" => 5
            ],
            [
                "id" => 63,
                "name" => "John Smith",
                "role" => "applicant",
                "email" => "johnsmith@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("johnsmith"),
                "phone" => "0177 123456",
                "linkedin_profile" => "johnsmith",
                "language" => "fr",
                "timezone" => "Europe/Paris",
                "mfa" => false,
                "avatar" => "johnsmith.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 1
            ],
            [
                "id" => 64,
                "name" => "Emma Johnson",
                "role" => "applicant",
                "email" => "emmajohnson@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("emmajohnson"),
                "phone" => "0152 987654",
                "linkedin_profile" => "emmajohnson",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "emmajohnson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 0
            ],
            [
                "id" => 65,
                "name" => "John Ross",
                "role" => "applicant",
                "email" => "johnross@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("johnross"),
                "phone" => "0160 345678",
                "linkedin_profile" => "johnross",
                "language" => "de",
                "timezone" => "Europe/Vienna",
                "mfa" => false,
                "avatar" => "johnross.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 3
            ],
            [
                "id" => 66,
                "name" => "Sarah Davis",
                "role" => "applicant",
                "email" => "sarahdavis@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("sarahdavis"),
                "phone" => "0173 654321",
                "linkedin_profile" => "sarahdavis",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "sarahdavis.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 2
            ],
            [
                "id" => 67,
                "name" => "Robert Anderson",
                "role" => "applicant",
                "email" => "robertanderson@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("robertanderson"),
                "phone" => "0151 876543",
                "linkedin_profile" => "robertanderson",
                "language" => "fr",
                "timezone" => "Europe/Paris",
                "mfa" => false,
                "avatar" => "robertanderson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 1
            ],
            [
                "id" => 68,
                "name" => "Laura Evans",
                "role" => "applicant",
                "email" => "lauraevans@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("lauraevans"),
                "phone" => "0176 234567",
                "linkedin_profile" => "lauraevans",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "lauraevans.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 0
            ],
            [
                "id" => 69,
                "name" => "James Wilson",
                "role" => "applicant",
                "email" => "jameswilson@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("jameswilson"),
                "phone" => "0154 567890",
                "linkedin_profile" => "jameswilson",
                "language" => "fr",
                "timezone" => "Europe/Paris",
                "mfa" => false,
                "avatar" => "jameswilson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 1
            ],
            [
                "id" => 70,
                "name" => "Megan Baker",
                "role" => "applicant",
                "email" => "meganbaker@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("meganbaker"),
                "phone" => "0162 890123",
                "linkedin_profile" => "meganbaker",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "meganbaker.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 2
            ],
            [
                "id" => 71,
                "name" => "Matthew Turner",
                "role" => "applicant",
                "email" => "matthewturner@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("matthewturner"),
                "phone" => "0157 456789",
                "linkedin_profile" => "matthewturner",
                "language" => "de",
                "timezone" => "Europe/Vienna",
                "mfa" => false,
                "avatar" => "matthewturner.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 3
            ],
            [
                "id" => 72,
                "name" => "Olivia Green",
                "role" => "applicant",
                "email" => "oliviagreen@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("oliviagreen"),
                "phone" => "0171 019283",
                "linkedin_profile" => "oliviagreen",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "oliviagreen.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 2
            ],
            [
                "id" => 73,
                "name" => "William Fisher",
                "role" => "applicant",
                "email" => "williamfisher@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("williamfisher"),
                "phone" => "0163 928374",
                "linkedin_profile" => "williamfisher",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "williamfisher.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 0
            ],
            [
                "id" => 74,
                "name" => "Jessica Allen",
                "role" => "applicant",
                "email" => "jessicaallern@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("jessicaallern"),
                "phone" => "0156 382947",
                "linkedin_profile" => "jessicaallern",
                "language" => "fr",
                "timezone" => "Europe/Paris",
                "mfa" => false,
                "avatar" => "jessicaallen.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 1
            ],
            [
                "id" => 75,
                "name" => "Christopher Murphy",
                "role" => "applicant",
                "email" => "christophermurphy@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("christophermurphy"),
                "phone" => "0178 374629",
                "linkedin_profile" => "christophermurphy",
                "language" => "de",
                "timezone" => "Europe/Vienna",
                "mfa" => false,
                "avatar" => "christophermurphy.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 3
            ],
            [
                "id" => 76,
                "name" => "Lily Griffin",
                "role" => "applicant",
                "email" => "lilygriffin@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("lilygriffin"),
                "phone" => "0161 293847",
                "linkedin_profile" => "lilygriffin",
                "language" => "fr",
                "timezone" => "Europe/Paris",
                "mfa" => false,
                "avatar" => "lilygriffin.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 1
            ],
            [
                "id" => 77,
                "name" => "Daniel Parker",
                "role" => "applicant",
                "email" => "danielparker@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("danielparker"),
                "phone" => "0153 849203",
                "linkedin_profile" => "danielparker",
                "language" => "fr",
                "timezone" => "Europe/Paris",
                "mfa" => false,
                "avatar" => "danielparker.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 1
            ],
            [
                "id" => 78,
                "name" => "Sophia Harris",
                "role" => "applicant",
                "email" => "sophiaharris@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("sophiaharris"),
                "phone" => "0179 203847",
                "linkedin_profile" => "sophiaharris",
                "language" => "fr",
                "timezone" => "Europe/Paris",
                "mfa" => false,
                "avatar" => "sophiaharris.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 1
            ],
            [
                "id" => 79,
                "name" => "Ethan Cook",
                "role" => "applicant",
                "email" => "ethancook@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("ethancook"),
                "phone" => "0166 203948",
                "linkedin_profile" => "ethancook",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "ethancook.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 0
            ],
            [
                "id" => 80,
                "name" => "Victoria Bell",
                "role" => "applicant",
                "email" => "victoriabell@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("victoriabell"),
                "phone" => "0159 102938",
                "linkedin_profile" => "victoriabell",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "victoriabell.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 0
            ],
            [
                "id" => 81,
                "name" => "John Doe",
                "role" => "applicant",
                "email" => "johndoe@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("johndoe"),
                "phone" => "0174 820394",
                "linkedin_profile" => "johndoe",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "johndoe.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 2
            ],
            [
                "id" => 82,
                "name" => "Jane Smith",
                "role" => "applicant",
                "email" => "janesmith@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("janesmith"),
                "phone" => "0164 203948",
                "linkedin_profile" => "janesmith",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "janesmith.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 2
            ],
            [
                "id" => 83,
                "name" => "Robert Johnson",
                "role" => "applicant",
                "email" => "robertjohnson@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("robertjohnson"),
                "phone" => "0155 203948",
                "linkedin_profile" => "robertjohnson",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "robertjohnson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 0
            ],
            [
                "id" => 84,
                "name" => "Sarah Williams",
                "role" => "applicant",
                "email" => "sarahwilliams@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("sarahwilliams"),
                "phone" => "0172 203948",
                "linkedin_profile" => "sarahwilliams",
                "language" => "fr",
                "timezone" => "Europe/Paris",
                "mfa" => false,
                "avatar" => "sarahwilliams.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 1
            ],
            [
                "id" => 85,
                "name" => "Michael Brown",
                "role" => "applicant",
                "email" => "michaelbrown@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("michaelbrown"),
                "phone" => "0168 203948",
                "linkedin_profile" => "michaelbrown",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "michaelbrown.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 2
            ],
            [
                "id" => 86,
                "name" => "Emily Davis",
                "role" => "applicant",
                "email" => "emilydavis@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("emilydavis"),
                "phone" => "0158 203948",
                "linkedin_profile" => "emilydavis",
                "language" => "de",
                "timezone" => "Europe/Vienna",
                "mfa" => false,
                "avatar" => "emilydavis.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 3
            ],
            [
                "id" => 87,
                "name" => "David Wilson",
                "role" => "applicant",
                "email" => "davidwilson@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("davidwilson"),
                "phone" => "0175 203948",
                "linkedin_profile" => "davidwilson",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "davidwilson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 0
            ],
            [
                "id" => 88,
                "name" => "Olivia Taylor",
                "role" => "applicant",
                "email" => "oliviataylor@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("oliviataylor"),
                "phone" => "0169 203948",
                "linkedin_profile" => "oliviataylor",
                "language" => "de",
                "timezone" => "Europe/Vienna",
                "mfa" => false,
                "avatar" => "oliviataylor.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 3
            ],
            [
                "id" => 89,
                "name" => "Mike Johnson",
                "role" => "applicant",
                "email" => "mikejohnson@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("mikejohnson"),
                "phone" => "0150 203948",
                "linkedin_profile" => "mikejohnson",
                "language" => "de",
                "timezone" => "Europe/Vienna",
                "mfa" => false,
                "avatar" => "mikejohnson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 3
            ],
            [
                "id" => 90,
                "name" => "Laura Hernandez",
                "role" => "applicant",
                "email" => "laurahernandez@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("laurahernandez"),
                "phone" => "0170 203948",
                "linkedin_profile" => "laurahernandez",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "laurahernandez.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 2
            ],
            [
                "id" => 91,
                "name" => "Adam Thompson",
                "role" => "applicant",
                "email" => "adamthompson@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("adamthompson"),
                "phone" => "0167 203948",
                "linkedin_profile" => "adamthompson",
                "language" => "fr",
                "timezone" => "Europe/Paris",
                "mfa" => false,
                "avatar" => "adamthompson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 1
            ],
            [
                "id" => 92,
                "name" => "Sarah Wilson",
                "role" => "applicant",
                "email" => "sarahwilson@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("sarahwilson"),
                "phone" => "0150 203948",
                "linkedin_profile" => "sarahwilson",
                "language" => "fr",
                "timezone" => "Europe/Paris",
                "mfa" => false,
                "avatar" => "sarahwilson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 1
            ],
            [
                "id" => 93,
                "name" => "David Lee",
                "role" => "applicant",
                "email" => "davidlee@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("davidlee"),
                "phone" => "0170 203948",
                "linkedin_profile" => "davidlee",
                "language" => "de",
                "timezone" => "Europe/Berlin",
                "mfa" => false,
                "avatar" => "davidlee.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 0
            ],
            [
                "id" => 94,
                "name" => "Olivia Brown",
                "role" => "applicant",
                "email" => "oliviabrown@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("oliviabrown"),
                "phone" => "0158 203948",
                "linkedin_profile" => "oliviabrown",
                "language" => "de",
                "timezone" => "Europe/Vienna",
                "mfa" => false,
                "avatar" => "oliviabrown.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 3
            ],
            [
                "id" => 95,
                "name" => "Alex Johnson",
                "role" => "applicant",
                "email" => "alexjohnson@applicant.com",
                "email_verified_at" => "2022-01-10",
                "password" => Hash::make("alexjohnson"),
                "phone" => "0164 203948",
                "linkedin_profile" => "alexjohnson",
                "language" => "en-US",
                "timezone" => "Europe/London",
                "mfa" => false,
                "avatar" => "alexjohnson.png",
                "remember_token" => Str::random(10),
                "created_at" => "2022-01-10",
                "updated_at" => "2022-01-10",
                "location_id" => 2
            ]
        ];

        DB::table('users')->insert($users);

        foreach ($users as $userData) {
            $user = User::find($userData['id']);

            if ($user->id == 0) {
                $user->assignRole($adminRole);
            }

            if ($user->id < 62) {
                $user->assignRole($recruiterRole);
            }

            if ($user->id >= 63) {
                $user->assignRole($applicantRole);
            }
        }
    }
}
